FROM ubuntu:20.04
RUN apt-get update && apt-get upgrade
RUN apt-get install php
RUN apt-get install php-pear php-fpm php-dev php-zip php-curl php-xmlrpc php-gd php-mysql php-mbstring php-xml libapache2-mod-php
