# /wordpress-docker/docker-compose.yml
---
version: "3.3"
services:
  db:
    container_name: "local-wordpress-db"
    image: "mysql:latest"
    volumes:
      - "./data/mysql:/var/lib/mysql"
    ports:
      - 18766:3306
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_password

  wordpress:
    container_name: "local-wordpress"
    depends_on:
      - db
    links:
      - db # this creates a network for both db and wordpress container can connect to
    image: "wordpress:latest"
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: "db:3306" # host is the container name for the database. This is how docker network works...
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress_db
    volumes:
      - "./wordpress:/var/www/html"
      - "./plugins:/var/www/html/wp-content/plugins"
